---
title: ETC3550/ETC5550 Applied forecasting
author: "Week 7: Seasonal exponential smoothing"
format:
  presentation-beamer:
    knitr:
      opts_chunk:
        dev: "cairo_pdf"
    pdf-engine: pdflatex
    fig-width: 7.5
    fig-height: 3.5
    include-in-header: ../header.tex
    keep_tex: yes
---


```{r setup, include=FALSE}
source(here::here("setup.R"))
library(patchwork)
library(gganimate)
library(purrr)
library(rlang)
library(magick)
```

## Historical perspective

 * Developed in the 1950s and 1960s as methods (algorithms) to produce point forecasts.
 * Combine a "level", "trend" (slope) and "seasonal" component to describe a time series.
 * The rate of change of the components are controlled by "smoothing parameters": $\alpha$, $\beta$ and $\gamma$ respectively.
 * Need to choose best values for the smoothing parameters (and initial states).
 * Equivalent ETS state space models developed in the 1990s and 2000s.


## ETS models

\begin{block}{}
\hspace*{-0.25cm}\begin{tabular}{l@{}p{2.3cm}@{}c@{}l}
\alert{General n\rlap{otation}}
    &                                        & ~E T S~           & ~:\hspace*{0.3cm}\textbf{E}xponen\textbf{T}ial \textbf{S}moothing \\ [-0.2cm]
    & \hfill{$\nearrow$\hspace*{-0.1cm}}     & {$\uparrow$}      & {\hspace*{-0.2cm}$\nwarrow$} \\
    & \hfill{\textbf{E}rror\hspace*{0.2cm}}  & {\textbf{T}rend}  & {\hspace*{0.2cm}\textbf{S}eason}
\end{tabular}
\end{block}

\alert{\textbf{E}rror:} Additive (`"A"`) or multiplicative (`"M"`)
\pause

\alert{\textbf{T}rend:} None (`"N"`), additive (`"A"`), multiplicative (`"M"`), or damped (`"Ad"` or `"Md"`).
\pause

\alert{\textbf{S}easonality:} None (`"N"`), additive (`"A"`) or multiplicative (`"M"`)


## ETS(A,A,A): Holt-Winters additive method 

\begin{block}{}\vspace*{-0.8cm}
\begin{align*}
\text{State equations}&& \ell_t&=\ell_{t-1}+b_{t-1}+\alpha \varepsilon_t\\
&&        b_t&=b_{t-1}+\beta \varepsilon_t \\
&&s_t &= s_{t-m} + \gamma\varepsilon_t \\
\text{Observation equation}&& y_t&=\ell_{t-1}+b_{t-1}+s_{t-m} + \varepsilon_t\\
\text{Forecast equation} && \hat{y}_{t+h|t} &= \ell_{t} + hb_{t} + s_{t+h-m(k+1)}
\end{align*}
\end{block}

  * Forecast errors: $\varepsilon_{t} = y_t - \hat{y}_{t|t-1}\sim\text{NID}(0,\sigma^2)$
  * $k$ is integer part of $(h-1)/m$.

## ETS(A,N,A): No trend, additive seasonal model

\begin{block}{}\vspace*{-0.8cm}
\begin{align*}
\text{State equations}&& \ell_t&=\ell_{t-1}+ \alpha \varepsilon_t\\
&&s_t &= s_{t-m} + \gamma\varepsilon_t \\
\text{Observation equation}&& y_t&=\ell_{t-1}+s_{t-m} + \varepsilon_t\\
\text{Forecast equation} && \hat{y}_{t+h|t} &= \ell_{t} + s_{t+h-m(k+1)}
\end{align*}
\end{block}

  * Forecast errors: $\varepsilon_{t} = y_t - \hat{y}_{t|t-1}\sim\text{NID}(0,\sigma^2)$
  * $k$ is integer part of $(h-1)/m$.

## Models so far

\fontsize{11}{12}\sf


\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Additive Error}} &        \multicolumn{3}{c}{\bf Seasonal Component}         \\
          \multicolumn{2}{c|}{\bf Trend}         &         N         &         A         &              \\
        \multicolumn{2}{c|}{\bf Component}       &     ~(None)~      &    (Additive)     & \phantom{(Multiplicative)}  \\ \cline{3-5}
           &                                     &                   &                   &  \\[-0.4cm]
  N        & (None)                              &       A,N,N       &       A,N,A       &         \\
           &                                     &                   &                   &  \\[-0.4cm]
  A        & (Additive)                          &       A,A,N       &       A,A,A       &         \\
  \phantom{A\damped}  & \phantom{(Additive damped)}                                 
\end{tabular}
\end{block}

\vspace*{10cm}

## All ETS models we will use
\fontsize{11}{12}\sf

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Additive Error}} &        \multicolumn{3}{c}{\bf Seasonal Component}         \\
          \multicolumn{2}{c|}{\bf Trend}         &         N         &         A         &         M         \\
        \multicolumn{2}{c|}{\bf Component}       &     ~(None)~      &    (Additive)     & (Multiplicative)  \\ \cline{3-5}
           &                                     &                   &                   &  \\[-0.4cm]
  N        & (None)                              &       A,N,N       &       A,N,A       &    A,N,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A        & (Additive)                          &       A,A,N       &       A,A,A       &    A,A,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                   &   A,A\damped,N    &   A,A\damped,A    & A,A\damped,M
\end{tabular}
\end{block}\pause

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Multiplicative Error}} &     \multicolumn{3}{c}{\bf Seasonal Component}      \\
             \multicolumn{2}{c|}{\bf Trend}            &      N       &         A         &        M         \\
           \multicolumn{2}{c|}{\bf Component}          &   ~(None)~   &    (Additive)     & (Multiplicative) \\ \cline{3-5}
           &                                           &              &                   &  \\[-0.4cm]
  N        & (None)                                    &    M,N,N     &       M,N,A       &      M,N,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A        & (Additive)                                &    M,A,N     &       M,A,A       &      M,A,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                         & M,A\damped,N &   M,A\damped,A    &   M,A\damped,M
\end{tabular}
\end{block}

\vspace*{10cm}

## ETS(M,N,N): SES with multiplicative errors.

\begin{block}{}\vspace*{-0.8cm}
\begin{align*}
\text{State equation}&& \ell_t              & = \ell_{t-1}(1+\alpha \varepsilon_t)\\
\text{Observation equation}&& y_t           & = \ell_{t-1}(1 + \varepsilon_t)\\
\text{Forecast equation} && \hat{y}_{t+h|t} & = \ell_t
\end{align*}
\end{block}

  * Relative forecast errors: $\varepsilon_{t}=\frac{y_t-\pred{y}{t}{t-1}}{\pred{y}{t}{t-1}} \sim\text{NID}(0,\sigma^2)$
  * Same point forecasts as ETS(A,N,N) with additive errors and same $\alpha$.
  * Different prediction intervals from ETS(A,N,N).

## ETS(M,A,N): Holt's method with multiplicative errors.

\begin{block}{}\vspace*{-0.8cm}
  \begin{align*}
      \text{State equations}&&\ell_t&=(\ell_{t-1}+b_{t-1})(1+\alpha \varepsilon_t)\\
      &&b_t&=b_{t-1}+\beta(\ell_{t-1}+b_{t-1}) \varepsilon_t\\
      \text{Observation equation}&&y_t&=(\ell_{t-1}+b_{t-1})(1+\varepsilon_t)\\
\text{Forecast equation} &&        \hat{y}_{t+h|t} &= \ell_{t} + h b_t
  \end{align*}
\end{block}

  * Relative forecast errors: $\varepsilon_{t}=\frac{y_t-\pred{y}{t}{t-1}}{\pred{y}{t}{t-1}} \sim\text{NID}(0,\sigma^2)$
  * Same point forecasts as ETS(A,A,N) with additive errors and same $\alpha$ and $\beta$
  * Different prediction intervals from ETS(A,A,N).

## ETS(M,A,M): Holt-Winters multiplicative method

\begin{block}{}\vspace*{-0.8cm}
\begin{align*}
\text{State equations}&& \ell_t&=(\ell_{t-1}+b_{t-1})(1+\alpha \varepsilon_t)\\
&&        b_t&=b_{t-1} +\beta(\ell_{t-1}+b_{t-1}) \varepsilon_t \\
&&s_t &= s_{t-m}(1 + \gamma\varepsilon_t) \\
\text{Observation equation}&& y_t&= (\ell_{t-1}+b_{t-1})s_{t-m}(1 + \varepsilon_t)\\
\text{Forecast equation} && \hat{y}_{t+h|t} &= (\ell_{t} + hb_{t}) s_{t+h-m(k+1)}
\end{align*}
\end{block}

  * Relative forecast errors: $\varepsilon_{t} = \frac{y_t - \hat{y}_{t|t-1}}{\hat{y}_{t|t-1}} \sim\text{NID}(0,\sigma^2)$
  * $k$ is integer part of $(h-1)/m$.

## ETS models
\fontsize{11}{12}\sf

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Additive Error}} &        \multicolumn{3}{c}{\bf Seasonal Component}         \\
          \multicolumn{2}{c|}{\bf Trend}         &         N         &         A         &         M         \\
        \multicolumn{2}{c|}{\bf Component}       &     ~(None)~      &    (Additive)     & (Multiplicative)  \\ \cline{3-5}
           &                                     &                   &                   &  \\[-0.4cm]
  N        & (None)                              &       A,N,N       &       A,N,A       &    A,N,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A        & (Additive)                          &       A,A,N       &       A,A,A       &    A,A,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                   &   A,A\damped,N    &   A,A\damped,A    & A,A\damped,M
\end{tabular}
\end{block}

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Multiplicative Error}} &     \multicolumn{3}{c}{\bf Seasonal Component}      \\
             \multicolumn{2}{c|}{\bf Trend}            &      N       &         A         &        M         \\
           \multicolumn{2}{c|}{\bf Component}          &   ~(None)~   &    (Additive)     & (Multiplicative) \\ \cline{3-5}
           &                                           &              &                   &  \\[-0.4cm]
  N        & (None)                                    &    M,N,N     &       M,N,A       &      M,N,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A        & (Additive)                                &    M,A,N     &       M,A,A       &      M,A,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                         & M,A\damped,N &   M,A\damped,A    &   M,A\damped,M
\end{tabular}
\end{block}

## Additive error models

\placefig{0}{1.5}{width=16.cm,trim=0 120 0 0,clip=true}{fig_7_ets_add.pdf}

## Multiplicative error models

\placefig{0}{1.5}{width=16.cm,trim=0 120 0 0,clip=true}{fig_7_ets_multi.pdf}


## ETS models
\fontsize{11}{12}\sf

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Additive Error}} &        \multicolumn{3}{c}{\bf Seasonal Component}         \\
          \multicolumn{2}{c|}{\bf Trend}         &         N         &         A         &         M         \\
        \multicolumn{2}{c|}{\bf Component}       &     ~(None)~      &    (Additive)     & (Multiplicative)  \\ \cline{3-5}
           &                                     &                   &                   &  \\[-0.4cm]
  N        & (None)                              &       A,N,N       &       A,N,A       &    A,N,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A        & (Additive)                          &       A,A,N       &       A,A,A       &    A,A,M     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                   &   A,A\damped,N    &   A,A\damped,A    & A,A\damped,M
\end{tabular}
\end{block}

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Multiplicative Error}} &     \multicolumn{3}{c}{\bf Seasonal Component}      \\
             \multicolumn{2}{c|}{\bf Trend}            &      N       &         A         &        M         \\
           \multicolumn{2}{c|}{\bf Component}          &   ~(None)~   &    (Additive)     & (Multiplicative) \\ \cline{3-5}
           &                                           &              &                   &  \\[-0.4cm]
  N        & (None)                                    &    M,N,N     &       M,N,A       &      M,N,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A        & (Additive)                                &    M,A,N     &       M,A,A       &      M,A,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                         & M,A\damped,N &   M,A\damped,A    &   M,A\damped,M
\end{tabular}
\end{block}

## ETS models
\fontsize{11}{12}\sf

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Additive Error}} &        \multicolumn{3}{c}{\bf Seasonal Component}         \\
          \multicolumn{2}{c|}{\bf Trend}         &         N         &         A         &         M         \\
        \multicolumn{2}{c|}{\bf Component}       &     ~(None)~      &    (Additive)     & (Multiplicative)  \\ \cline{3-5}
           &                                     &                   &                   &  \\[-0.4cm]
  N        & (None)                              &       A,N,N       &       A,N,A       &    \str{A,N,M}     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A        & (Additive)                          &       A,A,N       &       A,A,A       &    \str{A,A,M}     \\
           &                                     &                   &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                   &   A,A\damped,N    &   A,A\damped,A    & \str{A,A\damped,M}
\end{tabular}
\end{block}

\begin{block}{}
\begin{tabular}{ll|ccc}
  \multicolumn{2}{l}{\alert{\bf Multiplicative Error}} &     \multicolumn{3}{c}{\bf Seasonal Component}      \\
             \multicolumn{2}{c|}{\bf Trend}            &      N       &         A         &        M         \\
           \multicolumn{2}{c|}{\bf Component}          &   ~(None)~   &    (Additive)     & (Multiplicative) \\ \cline{3-5}
           &                                           &              &                   &  \\[-0.4cm]
  N        & (None)                                    &    M,N,N     &       M,N,A       &      M,N,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A        & (Additive)                                &    M,A,N     &       M,A,A       &      M,A,M       \\
           &                                           &              &                   &  \\[-0.4cm]
  A\damped & (Additive damped)                         & M,A\damped,N &   M,A\damped,A    &   M,A\damped,M
\end{tabular}
\end{block}

## AIC and cross-validation

\Large

\begin{alertblock}{}
Minimizing the AIC assuming Gaussian residuals is asymptotically equivalent to minimizing one-step time series cross validation MSE.
\end{alertblock}

## Automatic forecasting

**From Hyndman et al.\ (IJF, 2002):**

* Apply each model that is appropriate to the data.
Optimize parameters and initial values using MLE (or some other
criterion).
* Select best method using AICc:
* Produce forecasts using best method.
* Obtain forecast intervals using underlying state space model.

Method performed very well in M3 competition.

## Residuals
\vspace*{0.2cm}

### Response residuals
\centerline{$\hat{e}_t = y_t - \hat{y}_{t|t-1}$}

### Innovation residuals
Additive error model:
\centerline{$\hat\varepsilon_t = y_t - \hat{y}_{t|t-1}$}
Multiplicative error model:
\centerline{$\hat\varepsilon_t = \frac{y_t - \hat{y}_{t|t-1}}{\hat{y}_{t|t-1}}$}

