---
output: moodlequiz::moodlequiz
title: Assignment 1
moodlequiz:
  category: Assignment 1 Quiz
---

## Leaderboard name

*Optional*

At various points in the semester the rankings of the forecasts for this assignment will be featured in the lectures.

If you would like to appear on the forecasting accuracy leaderboard under an alias, you can enter it here: `r cloze_shortanswer(c("alias name" = 1))`.

## Q1 Forecasts

```{r, include = FALSE}
library(moodlequiz)
```

Produce a forecast of the Google (GOOG) closing stock price on 20 March 2024 in $USD (<https://finance.yahoo.com/quote/GOOG/> or <https://www.nasdaq.com/market-activity/stocks/goog/historical>).

The forecast mean: `r cloze_numerical(140, feedback = "Yes, that is a reasonable point forecast", tolerance = 100)`

The 80% forecast interval: [lower=`r cloze_numerical(140, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 100)`, upper=`r cloze_numerical(140, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 100)`]80%.

## Q1 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q2 Forecasts

Produce a forecast of the maximum temperature at Melbourne airport in degrees Celsius on
10 April 2024 (<http://www.bom.gov.au/climate/dwo/IDCJDW3049.latest.shtml/>)

The forecast mean: `r cloze_numerical(20, feedback = "Yes, that is a reasonable point forecast", tolerance = 20)`

The 80% forecast interval: [lower=`r cloze_numerical(20, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 20)`, upper=`r cloze_numerical(20, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 20)`]80%.

## Q2 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q3 Forecasts

Produce a forecast for the difference in points (Collingwood minus Essendon) scored in the AFL match between Collingwood and Essendon for the Anzac Day clash. 25 April 2024 (<https://en.wikipedia.org/wiki/Anzac_Day_match>).

The forecast mean: `r cloze_numerical(0, feedback = "Yes, that is a reasonable point forecast", tolerance = 100)`

The 80% forecast interval: [lower=`r cloze_numerical(0, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 100)`, upper=`r cloze_numerical(0, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 100)`]80%.

## Q3 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q4 Forecasts

Produce a forecast for the seasonally adjusted estimate of total employment (in persons) for April 2024. ABS CAT 6202, to be released around mid May 2024 (<https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia/latest-release>)

The forecast mean: `r cloze_numerical(14000000, feedback = "Yes, that is a reasonable point forecast", tolerance = 2000000)`

The 80% forecast interval: [lower=`r cloze_numerical(14000000, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 2000000)`, upper=`r cloze_numerical(14000000, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 2000000)`]80%.

## Q4 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q5 Forecasts

Produce a forecast of the Google (GOOG) closing stock price on 22 May 2024 in $USD (<https://finance.yahoo.com/quote/GOOG/> or <https://www.nasdaq.com/market-activity/stocks/goog/historical>).

The forecast mean: `r cloze_numerical(140, feedback = "Yes, that is a reasonable point forecast", tolerance = 100)`

The 80% forecast interval: [lower=`r cloze_numerical(140, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 100)`, upper=`r cloze_numerical(140, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 100)`]80%.

## Q5 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.
