---
title: Assignment 2
---

This assignment will use the same data that you will use in the [retail project](Project.qmd) later in the semester. Each student will use a different time series, selected using their student ID number as follows.

```r
library(fpp3)
get_my_data <- function(student_id) {
  set.seed(student_id)
  all_data <- readr::read_rds("https://bit.ly/monashretaildata")
  while(TRUE) {
    retail <- filter(all_data, `Series ID` == sample(`Series ID`, 1))
    if(!any(is.na(fill_gaps(retail)$Turnover))) return(retail)
  }
}
# Replace the argument with your student ID
retail <- get_my_data(12345678)
```

1. Using a test set of 2019--2022, fit an ETS model chosen automatically, and three benchmark methods to the training data. Which gives the best forecasts on the test set, based on RMSE?
2. Check the residuals from the best model using an ACF plot and a Ljung-Box test. Do the residuals appear to be white noise?
3. Now use time-series cross-validation with a minimum sample size of 15 years, a step size of 1 year, and a forecast horizon of 5 years. Calculate the RMSE of the results. Does it change the conclusion you reach based on the test set?
4. Which of these two methods of evaluating accuracy is more reliable? Why?

Submit a Quarto (`qmd`) file which carries out the above analysis. You need to submit one file which implements all steps above. You may use <a href="https://github.com/numbats/af/raw/main/assignments/Assignment_template.qmd">this file</a> as a starting point.

To receive full marks, the `qmd` file must compile without errors.

```{r}
#| output: asis
source(here::here("course_info.R"))
submit(schedule, "Assignment 2")
```
