---
title: Assignment 4
---

## Background

Here is a function that generates data from an AR(1) model starting with the first value set to 0

```r
generate_ar1 <- function(n = 100, c = 0, phi, sigma = 1) {
  # Generate errors
  error <- rnorm(n, mean = 0, sd = sigma)
  # Set up vector for the response with initial values set to 0
  y <- rep(0, n)
  # Generate remaining observations
  for(i in seq(2, length = n-1)) {
    y[i] <- c + phi * y[i-1] + error[i]
  }
  return(y)
}
```

Here `n` is the number of observations to simulate, `c` is the constant, `phi` is the AR coefficient, and `sigma` is the standard deviation of the noise. The following example shows the function being used to generate 50 observations

```r
library(fpp3)
tsibble(time = 1:50, y = generate_ar1(n=50, c=1, phi=0.8), index = time) |>
  autoplot(y)
```

## Instructions

<ol>
<li> Modify the `generate_ar1` function to generate data from any ARMA(p,q) model with parameters to be specified by the user. The first line of your function definition should be

  ```r
  generate_arma <- function(n = 100, c = 0, phi = NULL, theta = NULL, sigma = 1)
  ```

   Here `phi` and `theta` are vectors of AR and MA coefficients. Your function should return a numeric vector of length `n`.

   For example `generate_arma(n = 50, c = 2, phi = c(0.4, -0.6))` should return 50 observations generated from the model
   $$y_t = 2 + 0.4y_{t-1} - 0.6y_{t-2} + \varepsilon_t$$
   where $\varepsilon \sim N(0,1)$.

<li> The noise should be generated using the `rnorm()` function.

<li> Your function should check stationarity and invertibility conditions and return an error if either condition is not satisfied. You can use the `stop()` function to generate an error. The model will be stationary if the following expression returns `TRUE`:

  ```r
  !any(abs(polyroot(c(1,-phi))) <= 1)
  ```

  The MA parameters will be invertible if the following expression returns `TRUE`:

  ```r
  !any(abs(polyroot(c(1,theta))) <= 1)
  ```

<li> The above function sets the first value of every series to 0. Your function should fix this problem by generating more observations than required and then discarding the first few observations. You will need to consider how many observations to discard, to prevent the returned series from being affected by the initial values. Test that it is working by checking that the first few values of the series are close to the mean of the series, even when `c` is a large value.
</ol>

Please submit your solution as a .R file.

```{r}
#| output: asis
source(here::here("course_info.R"))
submit(schedule, "Assignment 4")
```
