---
output: moodlequiz::moodlequiz
title: Forecasting Competition
moodlequiz:
  category: Forecasting Competition Quiz
---

## Leaderboard name

*Optional*

At various points in the semester the rankings of the forecasts for this assignment will be featured in the lectures.

If you would like to appear on the forecasting accuracy leaderboard under an alias, you can enter it here: `r cloze_shortanswer(c("alias name" = 1))`.

## Q1 Forecasts

```{r, include = FALSE}
library(moodlequiz)
```

The 7-day moving average of transit trade volumes (in millions of metric tons) through the Strait of Hormuz on 7 August 2026. [Data](https://portwatch.imf.org/pages/cb5856222a5b4105adc6ee7e880a1730) *— click "Transit Trade Volume" tab*

The forecast mean: `r cloze_numerical(5, feedback = "Yes, that is a reasonable point forecast", tolerance = 5)`

The 80% forecast interval: [lower=`r cloze_numerical(5, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 5)`, upper=`r cloze_numerical(5, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 5)`]80%.

## Q1 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q2 Forecasts

Produce a forecast of the difference in runs scored between Australia and Bangladesh in the second cricket test to be held 22-26 August 2026, Mackay. Give result as (Australia total minus Bangladesh total). [Data](https://stats.espncricinfo.com/ci/engine/stats/index.html?class=1;opposition=2;opposition=25;orderby=start;team=2;team=25;template=results;type=team;view=match)

The forecast mean: `r cloze_numerical(0, feedback = "Yes, that is a reasonable point forecast", tolerance = 1000)`

The 80% forecast interval: [lower=`r cloze_numerical(0, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 1000)`, upper=`r cloze_numerical(0, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 1000)`]80%.

## Q2 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q3 Forecasts

Produce a forecast of the maximum temperature in Celsius at Melbourne airport on 13 September 2026. [Data](https://www.bom.gov.au/climate/dwo/IDCJDW3049.latest.shtml)

The forecast mean: `r cloze_numerical(25, feedback = "Yes, that is a reasonable point forecast", tolerance = 25)`

The 80% forecast interval: [lower=`r cloze_numerical(25, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 25)`, upper=`r cloze_numerical(25, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 25)`]80%.

## Q3 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q4 Forecasts

Produce a forecast of the Google (GOOG) closing stock price in $US on 5 October 2026. [Data](https://finance.yahoo.com/quote/GOOG/history/).

The forecast mean: `r cloze_numerical(400, feedback = "Yes, that is a reasonable point forecast", tolerance = 400)`

The 80% forecast interval: [lower=`r cloze_numerical(400, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 400)`, upper=`r cloze_numerical(400, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 400)`]80%.

## Q4 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.

## Q5 Forecasts

Produce a forecast for the seasonally adjusted estimate of the number of employed people (in millions) for September 2026. ABS CAT 6202, to be released on 15 October 2026. [Data](https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia/latest-release)

The forecast mean: `r cloze_numerical(15, feedback = "Yes, that is a reasonable point forecast", tolerance = 5)`

The 80% forecast interval: [lower=`r cloze_numerical(15, feedback = "Yes, that is a reasonable lower 80% bound", tolerance = 5)`, upper=`r cloze_numerical(15, feedback = "Yes, that is a reasonable upper 80% bound", tolerance = 5)`]80%.

## Q5 Explanation {type=essay}

Explanation of how you obtained your forecasts, no more than a couple of sentences.
